export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e4e9ed",
        "error": "#ba1a1a",
        "surface-container-low": "#f0f4f8",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#314863",
        "outline": "#74777e",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#44ddc1",
        "surface-variant": "#dfe3e7",
        "on-surface-variant": "#43474d",
        "surface": "#f6fafe",
        "inverse-primary": "#b0c9e8",
        "on-background": "#171c1f",
        "tertiary-container": "#002f27",
        "on-error-container": "#93000a",
        "inverse-surface": "#2c3134",
        "on-secondary-fixed-variant": "#2c4964",
        "secondary-fixed-dim": "#accaea",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#c3c6ce",
        "on-tertiary-container": "#00a28c",
        "on-primary-container": "#7a92b0",
        "inverse-on-surface": "#edf1f5",
        "secondary-container": "#bfddfe",
        "on-secondary-container": "#45627e",
        "surface-bright": "#f6fafe",
        "tertiary-fixed": "#68fadd",
        "primary": "#00152a",
        "on-tertiary-fixed": "#00201a",
        "surface-dim": "#d6dade",
        "tertiary": "#001813",
        "secondary": "#44617d",
        "on-surface": "#171c1f",
        "primary-fixed": "#d1e4ff",
        "background": "#f6fafe",
        "primary-container": "#102a43",
        "surface-container-highest": "#dfe3e7",
        "surface-container": "#eaeef2",
        "on-secondary-fixed": "#001d33",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "surface-tint": "#49607c",
        "secondary-fixed": "#cee5ff",
        "primary-fixed-dim": "#b0c9e8",
        "on-tertiary-fixed-variant": "#005145",
        "on-primary-fixed": "#011d35"
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Public Sans", "sans-serif"],
        label: ["Public Sans", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      boxShadow: {
        ambient: "0 20px 40px rgba(1, 29, 53, 0.06)",
        "ambient-sm": "0 10px 20px rgba(1, 29, 53, 0.04)",
      },
    },
  },
  plugins: [],
};